create table
  public.items (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    amount numeric not null,
    name text not null,
    constraint items_pkey primary key (id)
  ) tablespace pg_default;